version: '3'
services:

  tweeter_collector:
    build: tweet_collector/
    volumes:
    - ./tweet_collector:/code_tweet
    - ./logs:/logs
    depends_on:
    - my_mongodb  

  slackbot:
    build: slackbot/
    volumes:
    - ./slackbot:/code_bot
    - ./logs:/logs
    depends_on:
    - my_postgresdb

  etl:
    build: etl/
    volumes:
    - ./etl:/code_etl
    - ./logs:/logs
    depends_on:
    - my_mongodb
    - my_postgresdb

  my_mongodb:
    image: mongo
    ports:
    - 27018:27017

  my_postgresdb:
    image: postgres
    ports:
    - 5435:5432
    restart: always
    environment:
      POSTGRES_USER: spiced
      POSTGRES_PASSWORD: tweet_bot
      POSTGRES_DB: sentiment_db
  